CREATE TABLE IF NOT EXISTS `EVENT_LOG` (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  UUID CHAR(36) NOT NULL,
  USER_ID VARCHAR(32) NOT NULL,
  EVENT_CLASS_NAME VARCHAR(255) NOT NULL,
  OCCURRED_AT DATETIME NOT NULL,
  TOPIC VARCHAR(40),
  TARGET_ID CHAR(36),
  BODY LONGTEXT NOT NULL,
  RETRY_COUNT INT,
  FAIL_REASON  LONGTEXT,
  SEND_QUEUE_STATUS VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `EVENT_IDEMPOTENT_LOG` (
  EVENT_TYPE VARCHAR(190) NOT NULL,
  UNIQUE_KEY VARCHAR(64) NOT NULL,
  TARGET_ID CHAR(36),
  CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_TYPE, UNIQUE_KEY),
  KEY `idx_type_key` (`EVENT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `DISTRIBUTED_LOCK` (
    LOCK_KEY   VARCHAR(100) NOT NULL,
    OWNER_ID      VARCHAR(100) NOT NULL,
    EXPIRES_AT    TIMESTAMP(6) NOT NULL,
    CREATED_AT   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT pk_distributed_lock PRIMARY KEY (LOCK_KEY),
    CONSTRAINT uk_distributed_lock_lock_key UNIQUE (LOCK_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;