spring.application.name=send-email-module


#### MySQL ####
spring.datasource.url=jdbc:mysql://localhost:3306/sendmail?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=root

#### Spring Data JPA ####
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#### Mail ####
# 設定郵件服務的 SMTP 服務器。
spring.mail.host=localhost
# 設定郵件服務的 SMTP 服務器端口。
spring.mail.port=1025
# 設定郵件服務的用戶名。
spring.mail.username=''
# 設定郵件服務的密碼。
spring.mail.password=''
# 在郵件傳輸過程中使用 TLS（Transport Layer Security）加密協議，從而提高郵件的安全性，由於此處為測試故關閉
spring.mail.properties.mail.smtp.auth=false
# 設定郵件服務的 SMTP 身份驗證，由於此處為測試故關閉。
spring.mail.properties.mail.smtp.starttls.enable=false
# 發送郵件時等待寫入操作完成的最大時間（毫秒）。
spring.mail.properties.mail.smtp.writetimeout=5000


#### Quartz ####


#### kafka ####
# 告訴應用程式應該連接到哪一個或哪幾個 Kafka broker 來發送和接收消息
spring.kafka.bootstrap-servers=localhost:9092


## Producer 配置
# 發生錯誤，重送次數
spring.kafka.producer.retries=5 
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1

## Consumer 配置
spring.kafka.consumer.auto-commit-interval=1000
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=group.mail
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.session.timeout.ms=15000

## Listener 配置
spring.kafka.listener.concurrency=5
#spring.kafka.listener.ack-mode=manual-immediate
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.ack-mode=record
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=DEBUG

# SendMailEvent 對應的目的地
messaging.topics.send-mail=topic.send-mail
messaging.consumer-group.send-mail=group.send-mail
messaging.topics.send-mail.dlt=topic.send-mail.DLT
messaging.consumer-group.send-mail.dlt=group.send-mail.DLT

### 事件類所在路徑
event.package.path=com.example.demo.infra.event.shared.event
